<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [1, 'Alto Orinoco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [1, 'Atabapo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [1, 'Atures']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [1, 'Autana']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [1, 'Manapiare']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [1, 'Maroa']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [1, 'Río Negro']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Anaco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Aragua']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Manuel Ezequiel Bruzual']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Diego Bautista Urbaneja']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Fernando Peñalver']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Francisco Del Carmen Carvajal']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'General Sir Arthur McGregor']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Guanta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Independencia']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'José Gregorio Monagas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Juan Antonio Sotillo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Juan Manuel Cajigal']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Libertad']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Francisco de Miranda']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Pedro María Freites']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Píritu']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'San José de Guanipa']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'San Juan de Capistrano']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Santa Ana']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Simón Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [2, 'Simón Rodríguez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [3, 'Achaguas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [3, 'Biruaca']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [3, 'Muñóz']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [3, 'Páez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [3, 'Pedro Camejo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [3, 'Rómulo Gallegos']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [3, 'San Fernando']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Atanasio Girardot']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Camatagua']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Francisco Linares Alcántara']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'José Ángel Lamas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'José Félix Ribas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'José Rafael Revenga']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Libertador']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Mario Briceño Iragorry']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Ocumare de la Costa de Oro']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'San Casimiro']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'San Sebastián']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Santiago Mariño']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Santos Michelena']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Tovar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Urdaneta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [4, 'Zamora']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Alberto Arvelo Torrealba']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Andrés Eloy Blanco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Antonio José de Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Arismendi']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Barinas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Cruz Paredes']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Ezequiel Zamora']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Obispos']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Pedraza']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Rojas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [5, 'Sosa']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Caroní']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Cedeño']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'El Callao']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Gran Sabana']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Heres']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Piar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Angostura (Raúl Leoni)']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Roscio']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Sifontes']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [6, 'Padre Pedro Chien']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Bejuma']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Carlos Arvelo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Diego Ibarra']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Guacara']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Juan José Mora']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Libertador']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Los Guayos']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Miranda']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Montalbán']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Naguanagua']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Puerto Cabello']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'San Diego']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'San Joaquín']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [7, 'Valencia']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [8, 'Anzoátegui']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [8, 'Tinaquillo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [8, 'Girardot']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [8, 'Lima Blanco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [8, 'Pao de San Juan Bautista']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [8, 'Ricaurte']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [8, 'Rómulo Gallegos']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [8, 'San Carlos']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [8, 'Tinaco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [9, 'Antonio Díaz']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [9, 'Casacoima']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [9, 'Pedernales']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [9, 'Tucupita']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Acosta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Buchivacoa']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Cacique Manaure']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Carirubana']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Colina']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Dabajuro']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Democracia']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Falcón']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Federación']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Jacura']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'José Laurencio Silva']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Los Taques']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Mauroa']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Miranda']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Monseñor Iturriza']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Palmasola']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Petit']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Píritu']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'San Francisco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Tocópero']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Unión']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Urumaco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [10, 'Zamora']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Camaguán']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Chaguaramas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'El Socorro']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'José Félix Ribas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'José Tadeo Monagas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Juan Germán Roscio']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Julián Mellado']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Las Mercedes']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Leonardo Infante']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Pedro Zaraza']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Ortíz']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'San Gerónimo de Guayabal']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'San José de Guaribe']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Santa María de Ipire']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [11, 'Sebastián Francisco de Miranda']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [12, 'Andrés Eloy Blanco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [12, 'Crespo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [12, 'Iribarren']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [12, 'Jiménez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [12, 'Morán']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [12, 'Palavecino']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [12, 'Simón Planas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [12, 'Torres']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [12, 'Urdaneta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Alberto Adriani']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Andrés Bello']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Antonio Pinto Salinas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Aricagua']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Arzobispo Chacón']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Campo Elías']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Caracciolo Parra Olmedo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Cardenal Quintero']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Guaraque']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Julio César Salas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Justo Briceño']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Libertador']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Miranda']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Obispo Ramos de Lora']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Padre Noguera']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Pueblo Llano']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Rangel']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Rivas Dávila']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Santos Marquina']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Tovar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Tulio Febres Cordero']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [13, 'Zea']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Acevedo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Andrés Bello']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Baruta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Brión']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Buroz']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Carrizal']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Chacao']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Cristóbal Rojas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'El Hatillo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Guaicaipuro']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Independencia']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Lander']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Los Salias']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Páez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Paz Castillo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Pedro Gual']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Plaza']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Simón Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Urdaneta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [14, 'Zamora']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Acosta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Aguasay']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Caripe']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Cedeño']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Ezequiel Zamora']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Libertador']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Maturín']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Piar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Punceres']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Santa Bárbara']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Sotillo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [15, 'Uracoa']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Antolín del Campo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Arismendi']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'García']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Gómez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Maneiro']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Marcano']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Mariño']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Península de Macanao']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Tubores']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Villalba']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [16, 'Díaz']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Agua Blanca']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Araure']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Esteller']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Guanare']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Guanarito']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Monseñor José Vicente de Unda']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Ospino']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Páez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Papelón']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'San Genaro de Boconoíto']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'San Rafael de Onoto']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Santa Rosalía']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [17, 'Turén']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Andrés Eloy Blanco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Andrés Mata']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Arismendi']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Benítez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Bermúdez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Cajigal']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Cruz Salmerón Acosta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Libertador']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Mariño']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Mejía']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Montes']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Ribero']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [18, 'Valdéz']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Andrés Bello']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Antonio Rómulo Costa']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Ayacucho']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Cárdenas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Córdoba']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Fernández Feo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Francisco de Miranda']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'García de Hevia']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Guásimos']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Independencia']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Jáuregui']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'José María Vargas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Junín']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Libertad']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Libertador']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Lobatera']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Michelena']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Panamericano']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Pedro María Ureña']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Rafael Urdaneta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Samuel Darío Maldonado']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'San Cristóbal']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Seboruco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Simón Rodríguez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Torbes']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'Uribante']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [19, 'San Judas Tadeo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Andrés Bello']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Boconó']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Candelaria']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Carache']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Escuque']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'José Felipe Márquez Cañizalez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Juan Vicente Campos Elías']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'La Ceiba']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Miranda']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Monte Carmelo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Motatán']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Pampán']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Pampanito']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Rafael Rangel']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'San Rafael de Carvajal']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Trujillo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Urdaneta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [20, 'Valera']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [21, 'Vargas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Arístides Bastidas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Bruzual']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Cocorote']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Independencia']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'José Antonio Páez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'La Trinidad']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Manuel Monge']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Nirgua']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Peña']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'San Felipe']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'Urachiche']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [22, 'José Joaquín Veroes']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Almirante Padilla']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Baralt']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Cabimas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Catatumbo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Colón']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Francisco Javier Pulgar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Páez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Jesús Enrique Losada']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Jesús María Semprún']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'La Cañada de Urdaneta']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Lagunillas']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Machiques de Perijá']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Mara']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Maracaibo']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Miranda']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Rosario de Perijá']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'San Francisco']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Santa Rita']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Simón Bolívar']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Sucre']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [23, 'Valmore Rodríguez']);
        DB::insert('INSERT INTO cities (department_id, name) VALUES (?, ?)', [24, 'Libertador']);
    }
}
